on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:  

 build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.10 --android=10.2

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.0.x'

    - name: Build
      run: |
        cd TutorApp
        nuget restore
        cd TutorApp.Android
        msbuild TutorApp.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug

  Android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Android
      run: |
        cd TutorApp
        nuget restore
        cd TutorApp.Android
        msbuild TutorApp.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  iOS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: iOS
      run: |
        cd TutorApp
        nuget restore
        msbuild TutorApp.iOS/TutorApp.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug