on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        uses: rheuvel89/xamarin-container-action@v2
        with:
          SolutionPath: src/TutorApp.Android/TutorApp.Android.csproj
          ProjectPath: src/TutorApp.sln

  Android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Android
      run: |
        cd TutorApp
        nuget restore
        cd TutorApp.Android
        msbuild TutorApp.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  iOS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: iOS
      run: |
        cd TutorApp
        nuget restore
        msbuild TutorApp.iOS/TutorApp.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug