on:
    pull_request:
        branches:
            -main

jobs:        
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        cd TutorApp
        nuget restore
        cd TutorApp.Android
        msbuild TutorApp.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        cd TutorApp
        nuget restore
        msbuild TutorApp.iOS/TutorApp.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug